# Numpy Tutorials

### Advanced Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30, 40, 50])
a[[0, 2, 4]]

array([10, 30, 50])

In [3]:
b = a[[0, 2]]
b[0] = 100
print(a)
print(b)

[10 20 30 40 50]
[100  30]


In [4]:
A = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

A[[0, 2], [0,2]]

array([10, 90])

In [6]:
A[np.ix_([0, 2], [0, 2])]

array([[10, 30],
       [70, 90]])

In [7]:
np.random.randn(100, 50)

array([[ 0.7396574 , -2.15317127, -0.86171706, ..., -0.03335512,
        -0.03678689,  0.0700307 ],
       [ 0.06644194,  0.65050263, -0.06040162, ...,  0.15632213,
        -0.81521885, -2.55243722],
       [-1.49406653,  1.57823425,  0.12701648, ...,  0.43673646,
        -0.42332264, -0.64867024],
       ...,
       [ 1.29524996, -0.22184722,  0.62922853, ..., -0.47544091,
         1.30313367,  1.28110597],
       [ 1.48787319, -0.53032547, -0.59177742, ..., -0.66779063,
         1.30438347,  1.01021783],
       [-0.05206581,  0.18921552, -0.48946023, ...,  0.32903995,
        -1.11436149,  0.99571741]])

In [8]:
np.random.rand(5)

array([0.16535382, 0.22543589, 0.86858081, 0.68987516, 0.52692423])

In [9]:
np.random.uniform(10, 20, size=5)

array([18.58312619, 19.5684069 , 12.44602295, 11.9293003 , 11.3168913 ])

In [ ]:
np.random.normal(
    loc=50, # Mean
    scale=10, # Standard Deviation
    size=5
)

array([53.22664298, 60.21960667, 62.35697318, 53.33910664, 52.69587745])

In [ ]:
np.random.binomial(
    n=10, # No of trials
    p=0.5, # Probability
    size=5
)

array([4, 6, 3, 4, 5])

In [13]:
np.random.seed(42)

print(np.random.rand(3))


[0.37454012 0.95071431 0.73199394]


In [14]:
print(np.random.rand(3))

[0.59865848 0.15601864 0.15599452]


In [19]:
rng = np.random.default_rng(42)
rng.random(5)

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735])

In [20]:
rng.normal(size=5)

array([-1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [21]:
rng.integers(0, 10, size=5)

array([5, 3, 1, 9, 7])

### Structured Arrays

In [22]:
students = np.array([
    ("Alice", 20, 3.8),
    ("Bob", 22, 3.5),
    ("Charlie", 21, 3.9)
], dtype=[
    ("name", "U10"),
    ("age", "i4"),
    ("gpa", "f4")
])

In [23]:
students.dtype

dtype([('name', '<U10'), ('age', '<i4'), ('gpa', '<f4')])

In [24]:
students["age"]

array([20, 22, 21], dtype=int32)

In [25]:
students[0]["name"]

np.str_('Alice')

In [26]:
students[students["age"] > 20]

array([('Bob', 22, 3.5), ('Charlie', 21, 3.9)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('gpa', '<f4')])

### Excercises

1. Tasks:
- Compute square of all elements using:
    - Python loop
    - NumPy vectorization
- Compare execution time (use %timeit in Jupyter or manual timing)
- Compute:
    - sum of elements > 50
    - without loops

In [27]:
a = np.random.randint(1, 100, size=10_000)
a

array([75, 75, 88, ..., 59, 49, 63])

In [ ]:
%%timeit
a = np.random.randint(1, 100, size=10_000)
for i, val in enumerate(a):
    a[i] = val * val
print(a)

In [39]:
%%timeit
a * a

24.3 ns ± 1.15 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [ ]:
%%timeit
sum = 0
for val in a[a > 50]:
    sum += val

print(sum)


In [41]:
%%timeit
np.sum(a[a > 50])

1.6 μs ± 32.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [45]:
A = np.arange(1, 13).reshape(3, 4)

In [46]:
%%timeit
for row in A:
    pass

472 ns ± 71 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


2. Tasks
- Iterate row-wise (default)
- Iterate column-wise manually
- Check memory layout:

In [1]:
import numpy as np

A = np.arange(1, 13).reshape(3, 4)

In [5]:
for row in A:
    print(row)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [4]:
for col in A.T:
    print(col)

[1 5 9]
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]


In [6]:
A.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [7]:
B = np.array(A, order='F')

In [8]:
B.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Tasks
- Extract rows: [0, 2] using fancy indexing
- Extract columns: [1, 3]
- Extract elements:
    ```
    (0,0), (1,2), (3,1)
    ```
- Use np.ix_ to extract:
    ```
    [[ 2,  4],
    [10, 12]] 
    ```
- Use np.ix_ to extract:
    ```
    [[ 5,  6,  7,  8],
    [13, 14, 15, 16]]
    ```

In [11]:
A = np.arange(1, 17).reshape(4, 4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
A[[0,3]]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [14]:
A[:, [1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [15]:
A[[0, 1, 3], [0, 2, 1]]

array([ 1,  7, 14])

In [16]:
A[np.ix_([0, 2], [1, 3])]

array([[ 2,  4],
       [10, 12]])

In [19]:
A[np.ix_([1, 3], )]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])