# Numpy Tutorials

### Advanced Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30, 40, 50])
a[[0, 2, 4]]

array([10, 30, 50])

In [3]:
b = a[[0, 2]]
b[0] = 100
print(a)
print(b)

[10 20 30 40 50]
[100  30]


In [4]:
A = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

A[[0, 2], [0,2]]

array([10, 90])

In [6]:
A[np.ix_([0, 2], [0, 2])]

array([[10, 30],
       [70, 90]])

In [7]:
np.random.randn(100, 50)

array([[ 0.7396574 , -2.15317127, -0.86171706, ..., -0.03335512,
        -0.03678689,  0.0700307 ],
       [ 0.06644194,  0.65050263, -0.06040162, ...,  0.15632213,
        -0.81521885, -2.55243722],
       [-1.49406653,  1.57823425,  0.12701648, ...,  0.43673646,
        -0.42332264, -0.64867024],
       ...,
       [ 1.29524996, -0.22184722,  0.62922853, ..., -0.47544091,
         1.30313367,  1.28110597],
       [ 1.48787319, -0.53032547, -0.59177742, ..., -0.66779063,
         1.30438347,  1.01021783],
       [-0.05206581,  0.18921552, -0.48946023, ...,  0.32903995,
        -1.11436149,  0.99571741]])

In [8]:
np.random.rand(5)

array([0.16535382, 0.22543589, 0.86858081, 0.68987516, 0.52692423])

In [9]:
np.random.uniform(10, 20, size=5)

array([18.58312619, 19.5684069 , 12.44602295, 11.9293003 , 11.3168913 ])

In [ ]:
np.random.normal(
    loc=50, # Mean
    scale=10, # Standard Deviation
    size=5
)

array([53.22664298, 60.21960667, 62.35697318, 53.33910664, 52.69587745])

In [ ]:
np.random.binomial(
    n=10, # No of trials
    p=0.5, # Probability
    size=5
)

array([4, 6, 3, 4, 5])

In [13]:
np.random.seed(42)

print(np.random.rand(3))


[0.37454012 0.95071431 0.73199394]


In [14]:
print(np.random.rand(3))

[0.59865848 0.15601864 0.15599452]


In [19]:
rng = np.random.default_rng(42)
rng.random(5)

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735])

In [20]:
rng.normal(size=5)

array([-1.30217951,  0.1278404 , -0.31624259, -0.01680116, -0.85304393])

In [21]:
rng.integers(0, 10, size=5)

array([5, 3, 1, 9, 7])