# Numpy Tutorials

### Core Operations

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b) # Element Wise Operations

[11 22 33]


In [2]:
a = np.array([1, 2, 3])
print(a + 5) # Broadcasting

[6 7 8]


In [3]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([10,20,30]) # Row Broadcasting

print(a + b)


[[11 22 33]
 [14 25 36]]


In [4]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([
    [10],
    [20]
])

print(a + b) # Column Broadcasting

[[11 12 13]
 [24 25 26]]


In [5]:
a = np.array([10, 20, 30, 40])
print("Sum:", a.sum())
print("Mean:", a.mean())
print("Max:", a.max())
print("Min:", a.min())
print("Size:", a.size)

Sum: 100
Mean: 25.0
Max: 40
Min: 10
Size: 4


In [6]:
print("Standard Deviation:", a.std())
print("Variance:", a.var())

Standard Deviation: 11.180339887498949
Variance: 125.0


In [7]:
a = np.array([5, 12, 18, 3, 25])

(a > 10).sum()

np.int64(3)

In [8]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

a.sum(axis=0)

array([5, 7, 9])

In [9]:
a = np.array([10, 50, 30, 20])

print(a.argmax()) # Index
print(a.argmin())

1
0


In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)

print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(b.flatten())

[1 2 3 4 5 6]


In [12]:
print(b.T) # Transpose

[[1 4]
 [2 5]
 [3 6]]


In [13]:
a = np.array([[[1, 2, 3]]])

print(a.shape)
print(a.squeeze().shape) # Remove Single Dimensions

(1, 1, 3)
(3,)


### Excercise

In [14]:
a = np.array([1, 2, 3, 4, 5, 6])

In [15]:
print(a.reshape(3, 2))

[[1 2]
 [3 4]
 [5 6]]


In [16]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [18]:
np.expand_dims(a, axis=0)

array([[1, 2, 3, 4, 5, 6]])

In [19]:
np.expand_dims(a, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

1. Inspect the Array <br>
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])<br>
Print:
- shape
- size
- ndim
- dtype

In [20]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


2. Slicing Mastery<br>
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])<br>
Extract:
- First Row
- Last Row
- Second Column
- Last Column
- Submatrix: [[20 30]
 [50 60]]

In [37]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print("First Row:", arr[0])
print("Last Row:", arr[-1])
print("Second Column:", arr[[0, 1, 2],[1, 1, 1]])
print("Last Column:", arr[[0, 1, 2], [-1, -1, -1]])
print("Sub Matrix:", arr[0:2, 1:3])

First Row: [10 20 30]
Last Row: [70 80 90]
Second Column: [20 50 80]
Last Column: [30 60 90]
Sub Matrix: [[20 30]
 [50 60]]


3. Boolean Filtering<br>
scores = np.array([45, 67, 82, 31, 95, 58, 77])<br>
Tasks:
- Extract scores above 60
- Extract scores between 50 and 80
- Count scores below 50
- Replace all failing marks (<40) with 0

In [51]:
scores = np.array([45, 67, 82, 31, 95, 58, 77])

print("Scores above 60:", scores[scores > 60] )
print("Scores between 50 and 80:", scores[(scores > 50) & (scores < 80)])
print("Count scores below 50:", scores[scores < 60].size)

scores[scores < 40] = 0
print("Replace failing marks:", scores)

Scores above 60: [67 82 95 77]
Scores between 50 and 80: [67 58 77]
Count scores below 50: 3
Replace failing marks: [45 67 82  0 95 58 77]


4. Broadcasting and Arithmetic<br>
prices = np.array([100, 250, 80, 300])<br>
Compute:
- Price after 13% tax
- Price after Rs. 20 discount
- Double every price
- Find items costing more than Rs. 200


In [58]:
prices = np.array([100, 250, 80, 300])

print("Price after 13% tax:", prices + (prices * 0.13))
print("Price after Rs. 20 discount:", prices - 20)
print("Double prices:", prices * 2)
print("Items costing more than 200:", prices[prices > 200])



Price after 13% tax: [113.  282.5  90.4 339. ]
Price after Rs. 20 discount: [ 80 230  60 280]
Double prices: [200 500 160 600]
Items costing more than 200: [250 300]


5. Aggregations<br>
sales = np.array([
    [100, 120, 140],
    [90, 110, 150],
    [80, 130, 170]
])<br>
Find:
- Total sales
- Average sale
- Maximum sale
- Sum of each row
- Sum of each column
- Average of each column

In [66]:
sales = np.array([
    [100, 120, 140],
    [90, 110, 150],
    [80, 130, 170]
])

print("Total sales:", sales.sum())
print("Average sale:", sales.sum() / sales.flatten().size)
print("Maximum sale:", sales.max())
print("Sum of each row:", sales.sum(axis=0))
print("Sum of each column:", sales.sum(axis=1))
print("Average of each column:", sales.sum(axis=1)/sales.shape[1])

Total sales: 1090
Average sale: 121.11111111111111
Maximum sale: 170
Sum of each row: [270 360 460]
Sum of each column: [360 350 380]
Average of each column: [120.         116.66666667 126.66666667]


6. Argmax/Argmin<br>
scores = np.array([72, 88, 91, 65, 79])<br>
Find:
- Highest Score
- Index of highest score
- Lowest Score
- Index of lowest score


In [68]:
scores = np.array([72, 88, 91, 65, 79])
print(scores.max())
print(scores.argmax())
print(scores.min())
print(scores.argmin())

91
2
65
3
