# Numpy Tutorials

### Core Operations

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b) # Element Wise Operations

[11 22 33]


In [ ]:
a = np.array([1, 2, 3])
print(a + 5) # Broadcasting

[6 7 8]


In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([10,20,30]) # Row Broadcasting

print(a + b)


[[11 22 33]
 [14 25 36]]


In [6]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([
    [10],
    [20]
])

print(a + b) # Column Broadcasting

[[11 12 13]
 [24 25 26]]


In [9]:
a = np.array([10, 20, 30, 40])
print("Sum:", a.sum())
print("Mean:", a.mean())
print("Max:", a.max())
print("Min:", a.min())
print("Size:", a.size)

Sum: 100
Mean: 25.0
Max: 40
Min: 10
Size: 4


In [12]:
print("Standard Deviation:", a.std())
print("Variance:", a.var())

Standard Deviation: 11.180339887498949
Variance: 125.0


In [13]:
a = np.array([5, 12, 18, 3, 25])

(a > 10).sum()

np.int64(3)

In [15]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

a.sum(axis=0)

array([5, 7, 9])

In [ ]:
a = np.array([10, 50, 30, 20])

print(a.argmax()) # Index
print(a.argmin())

1
0


In [19]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)

print(b)

[[1 2 3]
 [4 5 6]]


In [20]:
print(b.flatten())

[1 2 3 4 5 6]


In [ ]:
print(b.T) # Transpose

[[1 4]
 [2 5]
 [3 6]]


In [22]:
a = np.array([[[1, 2, 3]]])

print(a.shape)
print(a.squeeze().shape) # Remove Single Dimensions

(1, 1, 3)
(3,)


### Excercise

In [30]:
a = np.array([1, 2, 3, 4, 5, 6])

In [25]:
print(a.reshape(3, 2))

[[1 2]
 [3 4]
 [5 6]]


In [26]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [32]:
np.expand_dims(a, axis=0)

array([[1, 2, 3, 4, 5, 6]])

In [33]:
np.expand_dims(a, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])