<h1>Numpy Tutorials</h1>

<h3>Core Foundations</h3>

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print("a.dtype (Data Type):",a.dtype)
print("a.ndim (Number of Dimensions):",a.ndim)
print("a.size:", a.size)

b = a.astype(float)
print(b.dtype)

[1 2 3 4 5]
a.dtype (Data Type): int64
a.ndim (Number of Dimensions): 1
a.size: 5
float64


In [9]:
c = np.zeros(5) # Array of 5 Zeros
print("np.zeros(5):", c)

c = np.ones(3) # Array of 3 Ones
print("np.ones(3):", c) 

c = np.full(4, 9) # Array of 4 Nines
print("np.full(4, 9):", c) 

c = np.arange(1,5,1) # Array of range 1 to 5?
print("np.arange(1, 5, 1):", c) 

c = np.linspace(1,5,9) # Array of Values from 1 to 5 (Split into Nine)
print("np.linspace(1, 5, 9):", c)

c = np.random.rand(5) # Array of random values from (0, 1]
print("np.random.rand(5):", c)

c = np.random.randn(10) # Array of random values where :: Mean = 0, SD = 1
print("np.random.randn(10):", c)

c = np.random.randint(5,7,5)
print("np.random.randint(5, 7, 5):", c)

np.zeros(5): [0. 0. 0. 0. 0.]
np.ones(3): [1. 1. 1.]
np.full(4, 9): [9 9 9 9]
np.arange(1, 5, 1): [1 2 3 4]
np.linspace(1, 5, 9): [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
np.random.rand(5): [0.04034368 0.54088442 0.95181834 0.14622314 0.7889094 ]
np.random.randn(10): [ 0.82528651 -0.55906592  0.43995051 -0.25960487 -0.31219016  1.16448926
 -0.52238435 -0.07325274  0.48011003 -1.06678096]
np.random.randint(5, 7, 5): [6 5 6 5 5]


In [22]:
a = np.array([10, 20, 30, 40, 50, 60])
print("a[1:3]:", a[1:3])

b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("b[2,0]:", b[2,0])

print("a[-2]:", a[-2])
print("b[-2, -1]:", b[-2, -1])

print("a[(a>10) & (a<40)]:", a[(a>10) & (a<40)])

a[1:3]: [20 30]
b[2,0]: 7
a[-2]: 50
b[-2, -1]: 6
a[(a>10) & (a<40)]: [20 30]


<h3>Excercises</h3>

1. Create this array:<br>
[10, 20, 30, 40, 50]<br>
Print: Shape, Dimensions, Size, Data Type

In [24]:
a = np.array([10, 20, 30, 40, 50])
print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Size:", a.size)
print("Data Type:", a.dtype)

Shape: (5,)
Dimensions: 1
Size: 5
Data Type: int64


2. Convert this list:<br>
[1, 2, 3, 4, 5] into float and boolean array

In [27]:
b = np.array([1, 2, 3, 4, 5])
print("Float: ", b.astype(float))
print("Boolean: ", b.astype(bool))

Float:  [1. 2. 3. 4. 5.]
Boolean:  [ True  True  True  True  True]


3. Create matrix: 
- 3X3 Matrix of zeros
- 2x4 Matrix of ones
- 3x3 Matrix of sevens

In [28]:
print("3x3 Matrix of zeros:\n", np.zeros((3,3)))
print("2x4 Matrix of ones:\n", np.ones((2,4)))
print("3x3 Matrix of sevens:\n", np.full((3,3), 7))

3x3 Matrix of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2x4 Matrix of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3x3 Matrix of sevens:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Replace all values < 10 with 0

In [30]:
c = np.array([1, 2 , 10, 12, 24, 50, 9, 3])
d = c.copy()
d[d < 10] = 0
print(d)

[ 0  0 10 12 24 50  0  0]


5. Extract Diagonal from np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d[[0, 1, 2],[0, 1, 2]]

array([1, 5, 9])

6. Extract all values divisible by 5.

In [32]:
print(d[d % 5 == 0])

[5]


7. Count how many values are > 15.

In [33]:
len(c[c > 15])

2