# Numpy Tutorials

### Linear Algebra

In [1]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [ ]:
a @ b # Matrix multiplication OR
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [4]:
a.T # Transpose

array([[1, 3],
       [2, 4]])

In [ ]:
np.eye(3) # Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linalg.det(a) # Determinant

np.float64(-2.0000000000000004)

In [ ]:
np.linalg.inv(a) # Inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
A = np.array([[2, 1],
              [1, 3]])

B = np.array([8, 13])

In [ ]:
x = np.linalg.solve(A, B) # Ax = B, We're finding x here
print(x)

[2.2 3.6]


In [10]:
Q, R = np.linalg.qr(a)
print("Orthogonal matrix Q:")
print(Q)
print("Upper triangular matrix R:")
print(R)

Orthogonal matrix Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
Upper triangular matrix R:
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [11]:
U, S, Vt = np.linalg.svd(a)
print("Left singular vectors (U):")
print(U)
print("Singular values (S):")
print(S)
print("Right singular vectors (V^T):")
print(Vt) 

Left singular vectors (U):
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular values (S):
[5.4649857  0.36596619]
Right singular vectors (V^T):
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [12]:
values, vectors = np.linalg.eig(a)
print("Eigenvalues:")
print(values)
print("Eigenvectors:")
print(vectors)

Eigenvalues:
[-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Excercises

1. Matrix Fundamental Operations

In [13]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

In [14]:
A + B

array([[ 6,  8],
       [10, 12]])

In [15]:
A * B

array([[ 5, 12],
       [21, 32]])

In [16]:
A @ B

array([[19, 22],
       [43, 50]])

In [17]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [18]:
A @ B == np.dot(A, B)

array([[ True,  True],
       [ True,  True]])

In [19]:
A.T

array([[1, 3],
       [2, 4]])

2. Inverse and Identify Matrix

In [20]:
A = np.array([
    [4, 7],
    [2, 6]
])

In [22]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [23]:
A @ A_inv

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]])

In [24]:
A_inv @ A

array([[1.00000000e+00, 6.66133815e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [25]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

3. Solving system<br>
2x + y = 7<br>
x + 3y = 11<br>

In [26]:
A = [[2, 1],
     [1, 3]]
b = [7, 11]

solution = np.linalg.solve(A, b)
solution

array([2., 3.])

4. Eigenvalues, Eigenvectors and Norm

In [27]:
A = np.array([
    [4, 2],
    [1, 3]
])

In [29]:
values, vectors = np.linalg.eig(A)
values

array([5., 2.])

In [30]:
vectors

array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]])

In [32]:
v = vectors[:, 0]
v

array([0.89442719, 0.4472136 ])

In [33]:
A @ v

array([4.47213595, 2.23606798])

In [34]:
values[0] * v

array([4.47213595, 2.23606798])

In [35]:
np.linalg.norm(v)

np.float64(0.9999999999999999)