# Numpy Tutorials

### Intermediate Power Tools

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))


[[1 2 3]
 [4 5 6]]


In [2]:
print(np.hstack((a, b)))

[1 2 3 4 5 6]


In [3]:
print(np.concatenate((a, b), axis=0))

[1 2 3 4 5 6]


In [5]:
a = np.array([1, 2, 3, 4, 5, 6])

print(np.split(a, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [7]:
a = np.array([1, 2, 3, 4, 5])

print(np.array_split(a, 2))

[array([1, 2, 3]), array([4, 5])]


In [8]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

np.split(a, 2, axis=0)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [9]:
np.split(a, 2, axis=1)

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

### Excercises

1. Tasks:
- Stack vertically using vstack
- Stack horizontally using hstack
- Try the same using concatenate

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("V Stack:\n", np.vstack((a, b)))
print("H Stack:\n", np.hstack((a, b)))
print("Concatenate(Horizontal):\n", np.concatenate((a, b), axis=0))

V Stack:
 [[1 2 3]
 [4 5 6]]
H Stack:
 [1 2 3 4 5 6]
Concatenate(Horizontal):
 [1 2 3 4 5 6]


2. Tasks:
- Concatenate with axis=0
- Concatenate with axis=1

In [19]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print(np.concatenate((a, b), axis=0))
print(":::::::::::::::::::::")
print(np.concatenate((a, b), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
:::::::::::::::::::::
[[1 2 5 6]
 [3 4 7 8]]


3. Tasks:
- Split into 2 equal parts (rows)
- Split into 3 column groups using array_split

In [25]:
data = np.array([
    [1, 2, 9],
    [3, 4, 10],
    [5, 6, 11],
    [7, 8, 12]
])

print(np.split(data, 2))
print(np.array_split(data, 3))

[array([[ 1,  2,  9],
       [ 3,  4, 10]]), array([[ 5,  6, 11],
       [ 7,  8, 12]])]
[array([[ 1,  2,  9],
       [ 3,  4, 10]]), array([[ 5,  6, 11]]), array([[ 7,  8, 12]])]
